"""Add Auditoria table

Revision ID: 1105a84c0951
Revises: 96ebe07c49fe
Create Date: 2026-10-03 20:21:02.743653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1105a84c0951'
down_revision: Union[str, Sequence[str], None] = '96ebe07c49fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Auditoria',
    sa.Column('id_auditoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Auditoria')
    # ### end Alembic commands ###
