"""initial schema

Revision ID: 945ad779f7a5
Revises: 
Create Date: 2026-10-03 18:33:35.011186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945ad779f7a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carregador',
    sa.Column('id_carregador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fabricante_modelo', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=False),
    sa.Column('potencia_nominal_kw', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tipo_conector', sa.String(), nullable=False),
    sa.Column('id_sems', sa.String(), nullable=False),
    sa.Column('estado_operacional', sa.String(), server_default='online', nullable=False),
    sa.PrimaryKeyConstraint('id_carregador'),
    sa.UniqueConstraint('id_sems')
    )
    op.create_table('Configuracao',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('Tarifa',
    sa.Column('id_tarifa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referencia_mes_ano', sa.String(), nullable=False),
    sa.Column('distribuidora', sa.String(), nullable=False),
    sa.Column('valor_kwh_centavos', sa.Integer(), nullable=False),
    sa.Column('bandeira_vigente', sa.String(), nullable=False),
    sa.Column('adicional_bandeira_centavos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('taxa_infraestrutura_centavos', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id_tarifa')
    )
    op.create_table('Unidade',
    sa.Column('id_unidade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=False),
    sa.Column('cd_unidade', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), server_default='residencial', nullable=False),
    sa.Column('status', sa.String(), server_default='ativo', nullable=False),
    sa.PrimaryKeyConstraint('id_unidade')
    )
    op.create_table('Usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('tipo_vinculo', sa.String(), nullable=True),
    sa.Column('id_rfid', sa.String(), nullable=True),
    sa.Column('id_app', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='MORADOR', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Fatura',
    sa.Column('id_fatura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_tarifa', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('politica_rateio', sa.String(), nullable=False),
    sa.Column('energia_total_kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('qtd_sessoes', sa.Integer(), nullable=False),
    sa.Column('valor_variavel_centavos', sa.Integer(), nullable=False),
    sa.Column('valor_taxa_centavos', sa.Integer(), nullable=False),
    sa.Column('valor_total_centavos', sa.Integer(), nullable=False),
    sa.Column('status_pgto', sa.String(), server_default='pendente', nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_tarifa'], ['Tarifa.id_tarifa'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_fatura')
    )
    op.create_table('Reserva_Carregador',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carregador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('dt_inicio_agendado', sa.DateTime(), nullable=False),
    sa.Column('dt_fim_agendado', sa.DateTime(), nullable=False),
    sa.Column('status_reserva', sa.String(), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_carregador'], ['Carregador.id_carregador'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_table('Unidade_Usuario',
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_unidade', 'id_usuario')
    )
    op.create_table('Sessao_Recarga',
    sa.Column('id_sessao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sessao_sems', sa.String(), nullable=False),
    sa.Column('id_carregador', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('id_fatura', sa.Integer(), nullable=True),
    sa.Column('dt_inicio', sa.DateTime(), nullable=False),
    sa.Column('dt_fim', sa.DateTime(), nullable=True),
    sa.Column('energia_kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('potencia_media_kw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('potencia_max_kw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status_final', sa.String(), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_carregador'], ['Carregador.id_carregador'], ),
    sa.ForeignKeyConstraint(['id_fatura'], ['Fatura.id_fatura'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sessao'),
    sa.UniqueConstraint('id_sessao_sems')
    )
    op.create_table('Alerta',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('id_sessao', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('severidade', sa.String(), server_default='media', nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('resolvido', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_sessao'], ['Sessao_Recarga.id_sessao'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['Unidade.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    op.create_table('Leitura_Medicao',
    sa.Column('id_leitura', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sessao', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('energia_acumulada_kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('potencia_instantanea_kw', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tensao_v', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('corrente_a', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_sessao'], ['Sessao_Recarga.id_sessao'], ),
    sa.PrimaryKeyConstraint('id_leitura')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Leitura_Medicao')
    op.drop_table('Alerta')
    op.drop_table('Sessao_Recarga')
    op.drop_table('Unidade_Usuario')
    op.drop_table('Reserva_Carregador')
    op.drop_table('Fatura')
    op.drop_table('Usuario')
    op.drop_table('Unidade')
    op.drop_table('Tarifa')
    op.drop_table('Configuracao')
    op.drop_table('Carregador')
    # ### end Alembic commands ###
