"""Add vehicle fields to Usuario

Revision ID: 96ebe07c49fe
Revises: 945ad779f7a5
Create Date: 2026-10-03 20:14:44.944240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ebe07c49fe'
down_revision: Union[str, Sequence[str], None] = '945ad779f7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('veiculo_modelo', sa.String(), nullable=True))
    op.add_column('Usuario', sa.Column('veiculo_bateria_kwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuario', 'veiculo_bateria_kwh')
    op.drop_column('Usuario', 'veiculo_modelo')
    # ### end Alembic commands ###
